import Head from "next/head";
import React from "react";

export default function Header() {
  return (
    <Head>
      <title>Match-On</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="description" content="대학생을 위한 협업툴" />
    </Head>
  );
}
